# Generated by Django 5.0 on 2025-11-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accesscode",
            name="is_used",
        ),
        migrations.RemoveField(
            model_name="accesscode",
            name="max_attempts",
        ),
        migrations.RemoveField(
            model_name="accesscode",
            name="name",
        ),
        migrations.AddField(
            model_name="accesscode",
            name="max_attempts_per_user",
            field=models.IntegerField(
                default=0, help_text="Maximum test attempts per user (0 for unlimited)"
            ),
        ),
        migrations.AddField(
            model_name="testsession",
            name="user_name",
            field=models.CharField(
                default="Unknown User",
                help_text="Name of the user taking this test",
                max_length=200,
            ),
        ),
    ]
