# Generated by Django 5.0 on 2025-11-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_remove_accesscode_is_used_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsession",
            name="test_mode",
            field=models.CharField(
                choices=[
                    ("one_by_one", "Birma-bir (istalgan vaqtda yakunlash)"),
                    ("batch_25", "25 ta savol (hammasi birdan)"),
                ],
                default="batch_25",
                max_length=20,
            ),
        ),
    ]
